### ISSUE TITLE
unblock lumendex.io

### ISSUE THREAD

**Issue by lumendex** [stellar-expert/public-directory#134]
hello,
our project lumendex.io has been added to black list. this is a coordinated attack from our competitors that are reporting us for scam and phishing, which is totally untrue and erroneous.
our domain providers have been attacked with spam emails stating that we are phishing for security keys. this is totally false, nonetheless they have blocked our domains without checking the code. 

this group of people are reporting fake issues.

i also dont understand how could you blacklist us without checking the reports to see if they are true?!
i am attaching
[Screencast_from_10-01-2022_12_17_31_PM.webm](https://user-images.githubusercontent.com/114811179/193408290-cff5699d-2ea6-4333-9059-a5e7c3823b7d.webm)
 screen recording showing that none of the requests are going to our server.
we are just a UI for the decentralized exchange on horizon.stellar.org

please inspect the website
lumendex.online, inspect every pixel of it and unlock our lumendex.io domain and unblock our issueing wallet. 
Thank you,
Best Regards!

**Comment by orbitlens** [comment]
After consultation with several community members we came to consensus regarding your project. The domain and issuing accounts will remain in the blocklist.

**Comment by lumendex** [comment]
have you got any arguments for this?

**Comment by CryptoHobbyist** [comment]
There are claims to connections to real world assets that are not supported. Do you have factual information to support the claim that these tokens have actual connections to the real world assets?

**Comment by CryptoHobbyist** [comment]
@lumendex One of the biggest legal problems occurs when a token infringes on the Brand, Trademark, Logo of real world assets.

**Comment by lumendex** [comment]
> @lumendex There are claims to connections to real world assets that are not supported. Do you have factual information to support the claim that these tokens have actual connections to the real world assets?

can you provide evidence with those claims? We did not copy any brand or any other entity. If you claim so, pease provide evidence, otherwise you are just dumping words with no facts.

**Comment by lumendex** [comment]
> @lumendex One of the biggest legal problems occurs when a token infringes on the Brand, Trademark, Logo of real world assets.

disclaimers are posted everywhere on our website. we do not support or recommend any assets, except our own token LDEX.
