### ISSUE TITLE
SCAM DOMAINS - BIG LIST

### ISSUE THREAD

**Issue by quadrigaex** [stellar-expert/public-directory#302]
Hello! After 5-6 hours of intense searches on lobstr and stellar.expert, I found a lot of domains that are fraudulent and deceive stellar users by duplicating official or non-official assets and sending claims to different accounts in order to deceive them.

Thank you!

-- domains --

projects-jura.org
proiect-jura.org
vltol.digital
australianmines.digital
australlamines.digital
mearskcom.digital
stellar-aigo.co
the-iine.tech
proiectamaala.com
atomtechnoiogy.tech
steliaraustralia.org
lrdigitalbanking.capital
pr0jectaurum.org
azurequatum.gold
us.g7digltal.pw
projectbayut.digital
beiarus-asset.digital
ximjackpot.online
blsinnovations.capital
cryptoafrican-asset.digital
casper-gold.digital
steliar-caribbean.digital
cb0b.digital
pr0jectceer.com
proiectcftc.com
projectctfc.com
earthpr0jectalpha.com
earthproiectalpha.com
theiine-stellar.org
projectcnap.com
coidquanta.digital
r3netw0rk.org
projectcorda.com
dbsbetterworid.io
ddw.fund
ewhip.org
exlm.global
steliareba.com
elonbank.org
eion.technology
eioncash.org
exllm.org
exlmq.org
elontrade.org
emlnlng.org
elightning.org
steliar-germany.digital
steliarguyana.net
steliarhedera.com
hellum.tech
steliar-hongkong.digital
hyper-iedger.org
steiiar-iran.digital
lmf-fund.com
imfsteliar.digital
stellar-indusin.digital
steliar-iota.com
stellarireiand.com
steiiar-japan.digital
steiiar-kuwait.digital
lcxprotocoi.com
iumendex.trade
iumendex.online
project-igold.digital
stellar-maidivies.digital
master-n0de.org
master-node.digital
steliar-myanmar.digital
mtls.gold
pr0ject-morpheus.org
project-morphues.org
netc0in.gold
netcoln.gold
newdawm.gold
projectbiuebeam.org
projects-jura.org
pr0jectustn.com
projectustn.digital
qanonproiect.digital
onet.gold
overiedger.tech
reb0rnx.org
russia-asset.digital
s7space-steiiar.org
steiiarsandbox.io
sap-cash.digital
satoshi-pay.digital
satoshl-pay.org
thesavlor.gold
thesavi0r.gold
sbisteilar.com
stellarsimba.digital
proiect-spia.com
steliarburkinafaso.com
stellarcoiumbia.com
steiiarcongo.com
steliar-cuba.digital
steliarguinea.com
steiiarmali.com
steiiarsouthafrica.com
steliarsudan.com
steiiarswift.org
steliartanzania.com
steliarukraine.org
steiiar-union.com
stellar-unlx.digital
strangew0rks.digital
strangework.digital
tiam0nds.io
tlamond.io
trust-bank.digital
uninnovation.org
vdc.systems
vletnam-assets.digital
steliar-armenia.digital
bisprojects.org
biuebeem.space
biuebeam.space
stellarboiivia.com
cryptoafrlcan-assets.digital
stellar-malaysia.com
projectspace-x.org
cmacqm.digital
projecthyperloop.org
thelinestellar.claims
mancltyfan.us
steliar-mauritius.com
projectnewdawn.gold
newdavvn.gold
steliar-russia.digital
saudivision-2030.digital
stronghold.claims
steliar-uae.digital
stepchian.co
turkmenistan-minerais.digital
cocso.bond
irdigitaibanking.capital
austraiiamines.digital
venezueiasteiiar.org
steiiarghana.com
steiiar-cuba.digital
vitol.claims
exlm.claims
e-rus.co
france-assets.org
projectguardian.claims
steiiarkyrgyzstan.com
projectledger.digital
sbisteiiar.com
steiiar-paraguay.digital
proiect1.pro
quantummetais.com
projectjura.org
s-switzeriand.com
steiiartajikstan.com
steiiar-uruguay.digital
steiiargibraltar.org
unlnnovatlons.org
stronghoid.co
steiiar-algo.co
cazper.gold
projectcorda.digital
ibmsolutions.claims
naturaigas.org
steiiarhedera.com
steiiar-hongkong.digital
heiium.tech
steiiar.claims
steiiar-indusln.digital
steiiar-maldivies.digital
steiiar-myanmar.digital
qnet.digital
lcxprotocol.claims
r3network.digital
s4p.cash
tiamonds.claims
whipiash.technology
xdco.org
steiiar-armenia.digital
stellarusa.claims
steiiaraustralia.org
brics.claims
steiiar-caribbean.digital
steilarcongo.com
dunbarproject.digital
blslnnovatlons.capital
steiiar-germany.digital
steiiarguinea.com
stellar-lran.digital
steiiarindia.dev
odinproject.digital
steiiar-russia.digital
s7space-steilar.org
steiiarsudan.com
projectseraphim.digital
stepchaln.co
steiiartanzania.com
projectviridis.digital
stellarargentlna.org
stellararmy.org
steiiar-bahrain.digital
steiiarburkinafaso.com
steiiarbolivia.com
steiiarcotedlvoire.com
earthprojectaipha.com
cmacmg.digital
steiiarcolumbia.com
cossco.bond
c0sc0.bond
steiiardominicanrepublic.com
eximp.org
g7digitai.pw
steilarindonesia.org
steliar-japan.digital
lumendex.claims
steiiarmoidova.org
steiiar-mauritius.com
steliarmexico.com
steilarmali.com
mits.gold
newdown.gold
0verledger.tech
projectoverledger.digital
the-pentagon.vip
steiiarperu.org
steiiarpapuanewguinea.com
ro-steiiar.co
steiiarbritain.digital
steiiarsuriname.com
trurnp.investments
steiiarturan.org
steiiar-uae.digital
steiiaruganda.org
whlplash.community
rippleasset.org
steliarsouthafrica.com
bfaiiiance.exchange
gesarastellar.solutions
qaskom.digital
stellar-kuwalt.digital
proiect-lgold.digital
nbus.digital
mbuz.digital
nesarastellar.solutions
pakistan-minerais.com
projectpeppo.tech
steiiarsyria.org
tradelens.claims
steliaruzbekistan.org
ruszoioto.gold
nvv3b.com
southafrica-asset.digital
steiiaralibaba.com
thewhitehats.vip
buigaria-minerals.digital
biackrock.claims
zinbabwe-mr.com
steiiarecuador.org
egyptpayment.org
eximbank.gold
stellarfema.digital
steiiarguyana.net
steiiarliberia.net
nevadamlnlng.gold
northkorea-asset.digital
poiand-minerals.digital
steiiarphilippines.net
steiiarsenegai.net
southkoreea-assets.digital
turkmenlstan-minerals.digital
steiiarukraine.org
vietnam-asset.digital
hyperiedger.org
steiiar-iota.com
steiiarireland.com
med-bed.technology
medbed.digital
master-nodes.org
thesavior.digital
atomtehnology.tech
proiectaurum.org
projectaurum.digital
azure-quantum.gold
proiectbayut.com
steiiar-beiarus.org
ixinium.claims
proiect-morpheus.org
sat0shi-pay.org
rebronx.org
strange-works.digital
quantumsystem.financial
metalsstellar.claims
dogecoln.com
proiectustn.com
qatarworldcup.claims
coldquant.digital
stellarsandbox.claims
stellarunix.com
kingsalmanpark.claims
projectamaaia.com
quantumassets.org
proiectceer.com
saudivisions-2030.com
stellarsimba.claims
dbsbetterworld.claims
stellareba.claims
unlnnovations.org
whlplash.technology
whipash.technology
nm3b.com
uk.g7digltal.pw
southafrlca-assets.digital
steiiaraiibaba.com
african-mr.com
africa-nr.com
de.g7digltal.pw
steliarghana.com
steilarusa.vip
it.g7digltal.pw
cb0n.digital
stellarchiie.com
zlmbabwe-mr.com
ca.g7digltal.pw
steliarcongo.com
fr.g7digltal.pw
stellardominicanrepubiic.com
steliarecuador.org
egyptpayment.com
eygptpayments.org
exlmbank.gold
steiiar-fema.digital
steliarsuriname.com
steiiarindonesia.org
keqss.digital
koyg.is
k0y.is
stellariiberia.net
stellarmoidova.org
stellarmadagascar.com
steiiarmexico.com
jp.g7digltal.pw
steliarniger.net
nevadamlning.gold
nevadaminings.gold
northkorean-assets.digital
poland-minerais.digital
the-pentagons.us
steiiarperu.net
stellarphiiippines.net
projectl.pro
projecti.pro
projectg0ld.digital
projectsgold.digital
proiectgold.digital
pr0jectguardian.digital
pr0jectaur0ra.me
steiiarsenegal.net
southkorea-asset.digital
steliarturan.org
steliaruganda.org
t0m0ke.io
transafrlca.vip
whipiash.community
whiplash.gold
stockstellar.org
siabet.org
ultrastellar.com
galiieomining.fund
bluegreengenie.xmint.io
bislnnovations.capital
bisinnovation.capital
ibmsolutions.co
elonssteliar.com
exlmr.org
kthouse.org
lovecoin.stellarmint.io
peppo.technology
project-1.pro
quantums.xmint.io
ro-stellar.com
sportsbook.stellarmint.io
syngentia.tech
tradeiens.co
abletoken.stellarmint.io
ac.stellarmint.io
amnesty.stellarmint.io
stellarspace.stellarmint.io
antipedo.stellarmint.io
argy.stellarmint.io
bitrue.stellarsquare.org
brave-token.age-shield.com
stelarpro.stellarmint.io
ctgx.stellarmlnt.io
flare-finance.org
doge-token.com
lobstr.co
epldoge.stellarmint.io
steliarrussia.io
elon-steilar.org
floki.stellardevelopers.org
grinpay.stellarsquare.org
kekistan.stellarmint.io
nanostellar.stellarmint.io
quantumstellar.org
qdoge.stellarmint.io
quantumdollars.digital
stellardoge.com
st.undefined
stronghold.stellardevelopers.org
usdf.tech
vdoge.stellarmint.io
strongholdx.co
alisa.xmint.io
angrysquidgame.xmint.io
anoninu.stellarmint.io
stellar-exchange.com
artemis-gateway.com
both3.xlmpay.top
golden.stellar-gold.org
byte.xlmplay.top
agrotokens.xmint.io
drtoken.stellarmem.org
stellardogelon.com
elantra.org
flowerlife.xmint.io
kusamax.xmint.io
blm.stellarmint.io
load.xlmplay.top
stellar-mainnet.com
pumping.one
phub.stellarmint.io
agrotokenss.xmint.io
shaggy-token.com
smart-lands.net
smrt.xlmplay.top
social-truth.org
unitoken.web.app
x.xmint.io
interstellar-network.io
gold.indus.bond
quantum-system.financial
stellarlite.stellarmint.io
ocean.xmint.io

**Comment by CryptoHobbyist** [comment]
Thank you so much for your work. Belo is the working list that I have put together of over 2,000 domains. Shining the light on scammers is an almost never ending task. The concern is not for the failed and ill thought out token projects but the ones infringing on trademarks, brands, governments, or logos, and copycats of the original scams, And the priorty is the most recent ones. 

It would be an awsome help if you cross referenced your list and the ones on my list and reduced it to the ones I have not already found. There are a very few on your list that I would identify as useless meme tokens and failed projects but not scams. Those might be unsafe to invest in but are not overtly illegal as the problems I listed above.

https://docs.google.com/spreadsheets/d/1JCkWZ3X1h6kJKM6ZCZThDshK_whhNiTyGTV8R24Anho/edit?usp=sharing

**Comment by CryptoHobbyist** [comment]
@quadrigaex Thank you for your help. I've cross referenced your list with my original list and honed it down a little, but there is still a lot to keep us busy for a while. As I said the focus will be for the current ones being minted and will come back and work on these.
(still 170 new ones to me to review)
0verledger.tech
africa-nr.com
beiarus-asset.digital
bfaiiiance.exchange
bisprojects.org
bitrue.stellarsquare.org
brave-token.age-shield.com
c0sc0.bond
coidquanta.digital
cossco.bond
ddw.fund
doge-token.com
dogecoln.com
drtoken.stellarmem.org
dunbarproject.digital
e-rus.co
earthproiectalpha.com
egyptpayment.com
elantra.org
elightning.org
eximp.org
exlmbank.gold
flare-finance.org
floki.stellardevelopers.org
france-assets.org
golden.stellar-gold.org
grinpay.stellarsquare.org
ibmsolutions.claims
interstellar-network.io
iumendex.trade
ixinium.claims
keqss.digital
koyg.is
kthouse.org
lcxprotocol.claims
load.xlmplay.top
lumendex.claims
master-node.digital
mbuz.digital
med-bed.technology
medbed.digital
mtls.gold
naturaigas.org
nbus.digital
nesarastellar.solutions
netc0in.gold
nevadaminings.gold
nevadamlning.gold
newdavvn.gold
newdawm.gold
newdown.gold
northkorea-asset.digital
pakistan-minerais.com
poland-minerais.digital
pr0ject-morpheus.org
proiect-jura.org
proiect1.pro
proiectamaala.com
proiectcftc.com
projectbiuebeam.org
projectctfc.com
projectguardian.claims
projecthyperloop.org
projecti.pro
projectledger.digital
projectoverledger.digital
projectpeppo.tech
projectsgold.digital
projectspace-x.org
qaskom.digital
quantum-system.financial
quantumassets.org
reb0rnx.org
rebronx.org
rippleasset.org
ro-steiiar.co
s4p.cash
s7space-steilar.org
sap-cash.digital
sat0shi-pay.org
satoshi-pay.digital
saudivision-2030.digital
sbisteilar.com
shaggy-token.com
siabet.org
smart-lands.net
smrt.xlmplay.top
social-truth.org
st.undefined
steiiar-bahrain.digital
steiiar-fema.digital
steiiar-hongkong.digital
steiiar-indusln.digital
steiiar-japan.digital
steiiar-kuwait.digital
steiiar-mauritius.com
steiiar-paraguay.digital
steiiar-uae.digital
steiiar-union.com
steiiar-uruguay.digital
steiiar.claims
steiiarbolivia.com
steiiarcotedlvoire.com
steiiarghana.com
steiiargibraltar.org
steiiarguyana.net
steiiarliberia.net
steiiarpapuanewguinea.com
steiiarperu.net
steiiarsenegai.net
steiiarsyria.org
steiiartajikstan.com
steiiarturan.org
steiiaruganda.org
steliar-japan.digital
steliar-myanmar.digital
steliar-uae.digital
steliarcongo.com
steliareba.com
steliaruzbekistan.org
stellar-exchange.com
stellar-maidivies.digital
stellararmy.org
stellardogelon.com
stepchaln.co
stockstellar.org
strangework.digital
stronghold.claims
stronghold.stellardevelopers.org
strongholdx.co
t0m0ke.io
the-pentagon.vip
thelinestellar.claims
thesavi0r.gold
tiam0nds.io
tiamonds.claims
trust-bank.digital
venezueiasteiiar.org
vitol.claims
whlplash.community
ximjackpot.online
artemis-gateway.com
 
agrotokens.xmint.io
agrotokenss.xmint.io
alisa.xmint.io
angrysquidgame.xmint.io
bluegreengenie.xmint.io
flowerlife.xmint.io
ocean.xmint.io
quantums.xmint.io
x.xmint.io
 
 
 
byte.xlmplay.top
both3.xlmpay.top
 
abletoken.stellarmint.io
amnesty.stellarmint.io
anoninu.stellarmint.io
argy.stellarmint.io
blm.stellarmint.io
epldoge.stellarmint.io
kekistan.stellarmint.io
lovecoin.stellarmint.io
nanostellar.stellarmint.io
phub.stellarmint.io
qdoge.stellarmint.io
sportsbook.stellarmint.io
stelarpro.stellarmint.io
stellarlite.stellarmint.io
stellarspace.stellarmint.io
vdoge.stellarmint.io
