### ISSUE TITLE
reporting a thief account

### ISSUE THREAD

**Issue by APUadmin** [stellar-expert/public-directory#409]
Hi
I want to report a thief account that steals many accounts seem to be, by creating additional valut signatures. This happened to me personally and I appreciate for helping to stop him or to return the XML he stole from other accounts.
Here is the full scenario history

- this account is got stolen GCVODN4OCJAM4TFVN6MGS33DPR3VWOG3N6IFG52A6ZDKXWVEEX57IFLL
using an account which created multisig with additional signature
GCLGDQ67SH33P3A3W3CTZLKIHSMLPCX4PNFMQQISMMQSERLSCYDNBDLP
So I can't control my account GCVODN4OCJAM4TFVN6MGS33DPR3VWOG3N6IFG52A6ZDKXWVEEX57IFLL anymore

- he used my account to create an offer to sell 
	2,495 AADC for XLM at 1 XLM/AADC
- he created an offer to buy the same AADC exactly using this account which may be he stolen it as well
GDECXQGKU2CG5GLIVJIJSCUGCXKTZ3TX3ZQ46XOIYLZFKM77NA7FROPR
because he controls its signature with the same account
GCLGDQ67SH33P3A3W3CTZLKIHSMLPCX4PNFMQQISMMQSERLSCYDNBDLP
- the money the XLM money he got, he transferred it to (himself)
GBQRA5ZFGKN6VQC6NBZTAIJLWBK5KWPWTSNWT6NQRTPSVWMHWX4ZDTF2
- then transferred it to his other account on Binance
GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A
with  Memo (TEXT): 280006335

is there any way to stop him from using the account 
GCVODN4OCJAM4TFVN6MGS33DPR3VWOG3N6IFG52A6ZDKXWVEEX57IFLL
or to freeze the AADC (Im the owner of its issuer account) which he has

**Comment by CryptoHobbyist** [comment]
[APUadmin](https://github.com/APUadmin) I will have some time to look into this tomorrow.

**Comment by CryptoHobbyist** [comment]
@APUadmin sadly there is nothing that Stellar.expert can do since this is only a Stellar blockchain explorer with it's own database to help users get information about the blockchain. You can file a police report and then use that to report to government officials who are investigating illegal crypto activity. Binance will not give the authorities and information about their 280006335 account without that report.

Other people can not just add themselves as signers. You either leaked your keys to someone, Someone helped you set up your project and they kept you key information, or you left your key information on your computer and it was hacked.

Your claim that someone used your account to set a buy order and sell order sounds like money laundering. Did you have a partner who your have since separated from who could have done this?

Looking Towards The Future With You,
Rob TheCryptoHobbyist

**Comment by CryptoHobbyist** [comment]
@APUadmin This is the transaction when the account set up the Lobstr wallet. 
https://stellar.expert/explorer/public/tx/192070958952439808#192070958952439809

**Comment by APUadmin** [comment]
Hi,
I mean Stellar.expert can mark his account as violating or a scam account
at the beginning. Then we can think about how he can hack many accounts. if
you check his account, I think he did the same with many accounts and
withdraw the money using Binance.
I contacted Binance and they stopped his account. they know who is he and
asked me to report him to the Police.
I contacted the FBI (They care about online criminals) and I'm gonna
contact the police as well.

I have seen the transaction you mentioned before and I was investigating it.
you can find it happened at the same time I got 2 XLM from that person. I
remember that I received 2 XLM and I think I have accepted it. but the
dates for all of that 3 operations (1 payment reception plus the 2 set
options) happend in a time which I wasn't doing anything related to the
lobstr. I have checked the history.

I'm working on that project on my own and didn't use any developers to set
up my accounts and I use my own computer. So it is hard to be hacked. The
key of the hacking I thought when I received that 2 xml (specially because
I think I already had enough XLM that enable him to make the trust line).
but on the other side. I found he did the same signature key hacking method
(which he uses to lock and control our accounts ) to hack other accounts as
well.

**Comment by CryptoHobbyist** [comment]
@APUadmin I'm not sure about a "signature key hacking method". Any information you have about that would be appreciated. How did you set up they wallet (what service did you use? Lobstr, stellarx, etc) and then how did you fund the account? These are two different activities. 

One of the common scams that I have seen is someone acting as an entity setups an wallet and then you fund the account. It looks like you have created the account but in reality the entity that helped set up the account has a copy of your keys. Setting up trustlines do not have any danger. No trustline is needed to be set up for XLM (the real native asset for the Stellar blockchain.)

**Comment by boydtech761** [comment]
Message https://t.me/boydtech on telegram he’s the best on account recovering

**Comment by CryptoHobbyist** [comment]
Hello @APUadmin 

Is there any update you can give to this situation or other requests you have?

**Comment by embeddedsystem2013** [comment]
Hi, Sorry for the delay in replying. A lot of work here to do. And discovered that he still makes more and more stealing and reported again to Binance.

 "signature key hacking method" > he simply gets able to get many private keys (Im not sure how) then he put his account as another signature. so the victim can't control his account anymore.

Sorry I didn't mean "trustline" , I meant "set options" he had to set  options that he is another signers, so he needed more XLM but im not sure of that, because it seems that I had enough XLM

regarding "entity setups" Do you mean something to create account ? like lobstr program  and https://laboratory.stellar.org/ ?

**Comment by APUadmin** [comment]
Hi, Sorry for the delay in replying. A lot of work here to do. And
discovered that he still makes more and more stealing and reported again to
Binance.

"signature key hacking method" > he simply gets able to get many private
keys (Im not sure how) then he put his account as another signature. so the
victim can't control his account anymore.

Sorry I didn't mean "trustline" , I meant "set options" he had to set
options that he is another signers, so he needed more XLM but im not sure
of that, because it seems that I had enough XLM

regarding "entity setups" Do you mean something to create account ? like
lobstr program and https://laboratory.stellar.org/ ?

**Comment by APUadmin** [comment]
I have set/created the account using https://laboratory.stellar.org

**Comment by CryptoHobbyist** [comment]
Hello @APUadmin,

If you were using the testnet, these are reset every so often and do not contain real/tradeable XLM. It is a sand box. But if you used the Public (https://horizon.stellar.org) system you should post your problems on the Discord server https://discord.gg/stellardev that has a lot of DEVs that might be able to help figure out what happened.

Looking Towards The Future With You,
Rob

**Comment by CryptoHobbyist** [comment]
Hello @APUadmin,

Please feel free to re open this issue if you have new information to let us know about.

Looking Towards The Future With You,
Rob

**Comment by CryptoHobbyist** [comment]
Have you tried to reach out to developers involved with the Stellar blockchain?
https://stellar.org/contact - a couple of possible sources
The Stellar Developers Discord is also very active

I personally still don't understand how you think the hacker was able to hack into your account without knowing your private key.

**Comment by APUadmin** [comment]
I think he hack our accounts because if you trace the hacker's activity, it
seems he hacked many accounts in a short time (sometimes was a few days
between each transfer from a stolen account to his account). so there is
some way that he could hack the private keys.
or maybe a fake site that was stealing the private keys. I can't remember
if I entered the private key in any unknown site actually. and if he has my
private key from the beginning why he had to send me 2 XLM first before he
could hack me?

**Comment by CryptoHobbyist** [comment]
Hello @APUadmin,

There are a large number of scammers who set up accounts (they have the keys) and then have you fund the account (sending the first 2 XLM). Funding the account then puts your address as the creator, when in reality they have the keys. Sometimes these scammers give you the keys so it really looks legit. But they still have a copy and later steal your assets. It is for this same reason you should never buy a cold wallet online except from the original manufacturer. 

Rob

**Comment by APUadmin** [comment]
Hi Rob,
But Im who created the account using the following link
https://laboratory.stellar.org/#?network=public
and I funded it. but after many many days. it seems that My XLM becomes low
then the thief sent to me 2 XLM then he could steal my account
however he didn't have to do the same with other victims

**Comment by CryptoHobbyist** [comment]
Hello @APUadmin,

Have you tried to reach out to developers involved with the Stellar blockchain?
https://stellar.org/contact - a couple of possible sources
The Stellar Developers on Discord.com is also very active
