### ISSUE TITLE
Unflag KingTroll.stellarmint.io

### ISSUE THREAD

**Issue by tacticalnoot** [stellar-expert/public-directory#480]
Issue with KingTroll.stellarmint.io assets being flagged, known by @CryptoHobbyist, initiating formal process of appeal per recommendation of @Spintax

**Comment by CryptoHobbyist** [comment]
@tacticalnoot do you have any specific addresses you can post that are flagged that need to be changed?

**Comment by tacticalnoot** [comment]
My specific request and current intent involves two assets. 

GQX - GD7TC72O5HML5UMZXQCIXGBR4KJ3MYM2ICPOR4BBN56K6JUSRVWTDAQF

AMM - GARQ7O5JPBD2DDVEFFZ2LVWH77BYSC7K7RMGI7W5GLRVSWPHZBNGBDOQ

**Comment by tacticalnoot** [comment]
Hello, 

This issue has not been resolved. 

The flag needs to be removed. 

These assets are under proper management and have addressed and corrected all behaviors and recommendations from the community.

**Comment by CryptoHobbyist** [comment]
Hello @tacticalnoot,

I'm closing this issue as unresolved I have not heard any new information from Orbitlens or you. As we had talked before you should post somewhere in your website full details about how you are running this private pool. Also have you made an effort to burn your earlier questionable tokens as to isolate this as the project you are using the domain for. (that is obviously your choice, but it would help spotlight on what you are focusing on)

Please feel free to reopen this issue if you have a full description URL to point to. The lable of "Independent Pool" with a caution would work with the circumstances. 

I hope you are able to transition this to a smart contract with locked assets and the coding to guarentee the reinjection of liquidity like you are currently working at.

Please feel free to reopen this issue with new information.

Looking Towards The Future With You,
Rob

**Comment by tacticalnoot** [comment]
Hi Rob! 

I’ve taken your feedback and altered the text on KingTroll.stellarmint.io and it’s TOML to contain the following text:

Organization Name
King Noot Enterprises
Organization Description
Weaving the hyperledger fabric of time thread-by-thread to make forever homes.

Active Projects: GQX and AMM.

Project Type: Private/Independent LP Assets and Building

Other projects on this TOML were released experimentally and could potentially be implemented in future with similar build models but no current plans exist for them unless otherwise indicated or proposed. Such projects could host individual third party groups for select builders.

Contact me on Twitter for inquiries.

https://StellarX.com/AMM/Liquidity
Organization Email Address
velvets.smarts0@icloud.com
Organization Physical Address
The United States
Organization Phone Number
[12692220332](tel:12692220332)
Organization Website
https://t.me/stellarverse
Twitter Account
[@tactical_noot](https://twitter.com/@tactical_noot)
Keybase.io Account
[tacticalnoot](https://keybase.io/tacticalnoot)

This revision includes the specificity of GQX and AMM being my active projects while still allowing the potential adoption of the other spaces for future shareholders to implement similar styles of building for themselves if they so choose. 

Due to the significant cutback in SDEX Volume over the last years, we chose two assets to permanently focus on, as the influencer-led group of 250K+ members this site was initially introduced to (as a freshman release candidate before full launch readiness) has since moved on to other things.

 The assets were intended to be sufficient and diverse for what appeared to be a large sample size, but with a move to my current group of well under 100 people, obviously things change. 
 
On the subject of burning them: I believe that they may be valuable properties to someone in the future and burning them could potentially impact the vision of any prospective implementer. At this time, all non-active projects are effectively in a dormant state and not being bought, sold, or marketed by the holder and are in what I assume is a decentralized stasis. There are basic LP’s constructed for them, and they can be expanded if desired. 
 
In the meantime, we’ve prepared GQX and AMM over the last two years for a significant amount of success and learned a lot in the process. 

In addition to this, I have included proper contact links to my X account and a good email to reach me. 

I hope this is a step in the right direction towards clarity. 

Regards,
TN

**Comment by tacticalnoot** [comment]
It should also be noted that while the other projects may not be the active focus of my development team, it is entirely possible that due to the nature of decentralization that people may be developing and contributing to their currency and my burning of tokens could potentially disrupt unseen ecosystems, so my decision not to intervene in the status of the non-active projects is a direct result of not wanting to interfere with that which cannot be seen.  

Let me know if the changes I’ve made thus far are sufficient, and if you have any additional advice 

I still want the projects unflagged and believe it I would be beneficial to the project and the Stellar Ecosystem as a whole to be able to see the work we’ve completed for GQXAMM.

**Comment by CryptoHobbyist** [comment]
Hello TN,

This looks really great. Have you built a page (have a link) explaining your "Private/Independent LP Assets and Building" project? I like the lable.

Rob

**Comment by CryptoHobbyist** [comment]
Have you played with smartcontracts?

**Comment by tacticalnoot** [comment]
Hey again, Rob!

It’s a stated goal of ours to have Soroban-ready versions of these assets, which we’ll begin developing in a greater capacity once Soroban is fully released, when even better tools are available, and the most complete version of the software exists to do so. 

I’ve dabbled a bit with Rust and Soroban but the consensus our team made was to learn as much as we can, and when it comes time to make that leap, we will!

 I’m not an IDE-type coder, so this endeavor is a completely new area of study for me, one that is inherently outside of the way that I learned crypto. 
 
Yes, I designed the pools, and direct its format, and guide its vision, but my strengths and the strengths of hard coding are entirely different. 

I’ll be watching closely and trying to learn, I have a close friend, shareholder, and contributor of the project who is much more suited to this who specializes in Python… once Soroban and Python get closer together, I’m told we’ll be closer. 

Now, THE SUBJECT AT HAND HERE:

Our status on Stellar Expert is destroying our ability to be recognized by many aggregates. I know you know what issues this causes, and I understand you can extrapolate that to be the root cause of reputational issues, and everything else that being in this status might have. 

For what it’s worth, I’ve made my absolute best effort to be in the utmost graces with everyone and have every intention to do so going forward. 

Tomer Weller’s reply to me was on his public X page. Stellar Org liked a comment I made about David Mazieres 2016 talk today. 

At this point, Stellar is recognizing me favorably more than Expert or any of its associates.

Please fix this issue. 
Thank you.

**Comment by tacticalnoot** [comment]
P.s. Almost every other Stellar site uses stellar.expert’s repository for their token data, and this categorization and flagging has made us practically invisible to prospective customers and community. This issue getting fixed is a key part of our future success and I implore you kindly to do what you can to make it right for this small and independent effort.

**Comment by CryptoHobbyist** [comment]
What web link can be used to proceed with changing the tagging/labeling?

**Comment by tacticalnoot** [comment]
Hi Rob! 

KingTroll.stellarmint.io is the website that I paid to host the TOML and describe the projects. The tokens are locked to this host and no additional tokens can be minted from GQX or AMM. 

The hosting is paid for until 2030; I had a discussion with the Stellarmint administrator and he granted me clearance and hosting until at least 2030. If Stellarmint continues to be as reliable as they have, I see no issue with continuing to use their service. They allow projects the opportunity to practice without prejudice, and I believe good things can come of that. 

If this domain can be cleared of the censors and properly allowed on Stellar Expert, I believe it would set a good and business-friendly example for creators everywhere. 

I understand the need to bring visibility to viable and reputable projects and have been working to restore credibility to the brand. 

Please allow us the visibility we need to do honest work. Think of it this way: You could clear our flags, allow us to practice, and give us a second chance to show you our intent to bring good things to this space in a unique and equitable way.

 If anything were to happen in future that affected our status, you could always reapply the censor.

This is a project that I’m very proud of, and I humbly request that you allow the world to see it. 

Thank you, 
TN

**Comment by CryptoHobbyist** [comment]
Hello @tacticalnoot,

All the details are not completely explained in the TOML file, which is not a problem. Do you, or can you, give a URL for a page that explains your system for your AMM and GQX tokens? This would be the most clear for any new investors.

I agree that with that information your project should have the warning tags removed/changed.

Rob

**Comment by tacticalnoot** [comment]
Hey Rob!

I have made a website. 

Check it out! 

https://gqxamm.wordpress.com/

- TN

**Comment by tacticalnoot** [comment]
Dear Rob, 

I have satisfactorily complied and cooperated with you about this issue and it is still open. 

Please assist me in repairing our brand; Stellar Expert is a major root in the tree of reputation, and ameliorating this will allow us not only vindication, but the opportunity to make Stellar a better place. 

Thank you.

**Comment by tacticalnoot** [comment]
Dear Rob,

Can you please validate this? 

Thank you.

**Comment by tacticalnoot** [comment]
Rob, 

You have not yet cleared the Warning Flag. You have merely added ANOTHER flag. This is not what we agreed upon. 

Please help me with this issue, it’s not fixed and it’s very important to me.

**Comment by CryptoHobbyist** [comment]
I have to get OrbitLens to stop blocking all tokens from your domain. I can only work on individual tokens. That has resulted in me not being able to remove the malious flag.

**Comment by tacticalnoot** [comment]
Hi Rob,

What’s the next step, then? You seem to want to help. This is good. I think you know by now my intentions are fully clear and good with this. 

Thank you and let me know what happens. 

Appreciate you standing behind me on this, honestly. I’ll do what I can to keep it going just as I have. 

Cheers.

**Comment by tacticalnoot** [comment]
Good Morning Rob. 

I see further changes have been made to this assets classification. 

It is no longer indicating illicit/fraud, but you still have it listed as unsafe. It is completely safe. 

This change has muddled it in amongst scam airdrop tokens and junk. 

This is COMPLETELY WRONG. 

Please recategorize this as a normal project and allow us to have our rating visibility back, without a hazard icon on its transaction tags etc! 

Please and thank you.

**Comment by CryptoHobbyist** [comment]
Hello,

At this point it is up to OrbitLens. Maybe you can appeal to him with all the details of your project. Don't assume that he will remember what you told him before.

Rob

**Comment by tacticalnoot** [comment]
Hey Rob,So he’s back around now? Last time I tried talking to him I couldn’t get a reply. Granted there are a few extra things we have towards our legitimacy now, and a track record of pool holders that are confirmably Holders and not “Cruisers”. (As noted by a generally known statistic called “Holder Composition”, which states that accounts holding for a period of 2-12 months are known as cruisers or swing traders, where one year+ of consistent holding of position, as we’ve done, merits the title “Holder”)I appreciate your valuable attention to this project as it helps us to set goals of relative stability and longevity. Our standards, commitment, regularity and liquidity are higher than many “Verified” projects here, and our goal to enhance and develop Stellar during these changing times is a commitment I take seriously. I understand that no project is perfect, and that Protocol 18 brought growing pains to our small Native locale, but please also understand that I was here far before, have learned much, and intend to stay. Please provide a way that I can reach him, or please reach out to him yourself about this, as you can vouch for the commitments we’ve made to addressing and resolving the issues. Thank youTNOn Dec 19, 2023, at 9:31 PM, CryptoHobbyist ***@***.***> wrote:﻿
Hello,
At this point it is up to OrbitLens. Maybe you can appeal to him with all the details of your project. Don't assume that he will remember what you told him before.
Rob
