### ISSUE TITLE
Meme mistake

### ISSUE THREAD

**Issue by dhoppus** [stellar-expert/public-directory#572]
efaae76bdbc12776dbd67103fda945311506f98166£63be0c38372be2dc953

Memo : 1527135629

**Comment by CryptoHobbyist** [comment]
Hello @dhoppus,

Can you please give some details about the issue you are reporting?

Looking Towards The Future With You,
Rob

**Comment by dhoppus** [comment]
Hello, Stellar-Expert/Public-Directory


There is mistake in memo which i copied.
The address which i copied is correct but the memo mistake.

Believe u will do the needful

With regards,

Dhoppu

**Comment by CryptoHobbyist** [comment]
Hello @dhoppus 

This efaae76bdbc12776dbd67103fda945311506f98166£63be0c38372be2dc953 is not a legitimate transaction ID,  ( £ ) is not a valid Hexadecimal digit.

I do not understand what that sequence is that you posted. Do you have a valid transaction ID to post. There is no MEMO needed to transfer assets into a Stellar Wallet. 

If you were sending to another exchange then you will need to contact that support team to get some help.

With that said, Stellar Expert is only a blockchain explorer that helps people to find information about transactions on the Stellar Blockchain without having to know coding. We maintain databases to help speed up this process. We also tag tokens and wallets to help people find out information about things on the blockchain, But Stellar Expert can not change or create activity on the Stellar Blockchain.

We can try to help you understand things that have happened but you will need to give us data that we can use:
Wallet addresses, Memos, Transaction ID, asset labels, etc. 

Looking Towards The Future With You.
Rob

**Comment by CryptoHobbyist** [comment]
Hello @dhoppus

Please feel free to reopen this issue if you have new information to post.

Looking Towards The Future With You,
Rob
