### ISSUE TITLE
Block domain lapo.io

### ISSUE THREAD

**Issue by broroduvce9p** [stellar-expert/public-directory#595]
1)
Perhaps the theft of ICO funds in 2018, since the active development stage ended almost 4 years ago. The project stopped showing signs of life after 2020.
https://foundico.com/person/luis-franceschi.html
https://icoholder.com/lapo-blockchain-19163

Funds raised: $7,373,914 or $40,257,067

lapo.io
The site was last updated in December 2021.

The roadmap for more than 4 years has been prescribing fake plans and values that change only year/percentage of progress once a year. Starting from 2020, nothing is being done at all.
https://web.archive.org/web/20190319014028/https://lapo.io/roadmap.html
https://web.archive.org/web/20200524191931/https://lapo.io/roadmap.html
https://web.archive.org/web/20210927222536/https://lapo.io/roadmap.html
https://web.archive.org/web/20220704154302/https://lapo.io/roadmap.html
https://web.archive.org/web/20230321211144/https://lapo.io/roadmap.html

https://medium.com/lapoblockchain

https://t.me/lapoblockchain
Closed to public viewing in the fall of 2019.

2)
Theft of funds by developers when exchanging between XLM/BSC networks
   #LAPO XLM/BSC Replacement machine

BSC Address Deposit
https://bscscan.com/address/0xc5017e37fb4ccb7ffd898caec0c43fb6dc55089a

List of deposits
https://bscscan.com/advanced-filter?tadd=0xc5017e37fb4ccb7ffd898caec0c43fb6dc55089a&txntype=2&tkn=0x082bb8716452Bf4E27E190ecf6efB89cCC7cd5C4
Total received 148607474.48412 LAPO BSC

Windraw XLM Address
https://stellar.expert/explorer/public/account/GAAXAMZCNLIT7YY6E4TDZZPYWLMCG7TSZUCOAU45FB4ZNAVGGOHE7KF5
Windraw XLM address 2
https://stellar.expert/explorer/public/account/GDKJ4YQ75DKPIC6FMR667GKAFXRKKTMAJ63UH4S7OMGVE4CXL26KVRET

Windraw List (Memo: Swap back)
https://stellar.expert/explorer/public/account/GAAXAMZCNLIT7YY6E4TDZZPYWLMCG7TSZUCOAU45FB4ZNAVGGOHE7KF5?account[]=GAAXAMZCNLIT7YY6E4TDZZPYWLMCG7TSZUCOAU45FB4ZNAVGGOHE7KF5&memo[]=Memo%3A %20 Swap%20back&type[]=payments
Sent 90552688 LAX XLM

Windraw 2 List (Memo: Swap back)
https://stellar.expert/explorer/public/account/GDKJ4YQ75DKPIC6FMR667GKAFXRKKTMAJ63UH4S7OMGVE4CXL26KVRET?account[]=GDKJ4YQ75DKPIC6FMR667GKAFXRKKTMAJ63UH4S7OMGVE4CXL26KVRET&memo[ ]=s wap&sort=id
Sent 32194529 LAX XLM

Total sent 122747217 LAX XLM

!!!Stolen by the developers:
148607474.48412 LAX BSC - 122747217 LAX XLM = -25860257.48412 LAPO BSC
The average price during that time period for 1 LAX = 0.00075/0.001 USD. (data from stellarterm and poocoin)
Stolen by developers in USD from 19395.2 USD to 25860.25 USD and removed from the liquidity of LAPO XLM (maybe more if you specify token rates)

**Comment by CryptoHobbyist** [comment]
Hello @broroduvce9p 

Are you reporting that this token project is dead due to internal fraud or are you reporting something else? I would agree that it looks like the project is dead with there BEP-20 token and the XLM market looks like it is just some people unaware and/or just trying to get what little they can. 

What was the "Swap Back"?

What kind of label are you suggesting?

As you know many token projects with good intitial intentions die due to poor execution. There are also DEVs that rug the project, not to be trusted DEVs that steal from the project or worse the customers directly, plain Ponzi schemes, out right pump and dumps, etc.

I have not dove into this much but initially it looks like a dead project that had devs (maybe just some bad actors) that drained the liquidity and killed it.

Your additional input is wanted. Can you clearly state what labels you think should be added to the Stellar Expert database?

Looking Towards The Future With You,
Rob

**Comment by broroduvce9p** [comment]
Exactly **#unsafe** label , from this dead dubious project the network will be better.
I think such a corpse is not even worth the time and how much xlm the developers stole. Only what was on the surface and can be checked through bsbscan and stellar.expert.

**Comment by CryptoHobbyist** [comment]
Hello @broroduvce9p

#unsafe dead is warrented, thank you for the report.

 Do you know what they were doing with the "Swap Back"?

Looking Towards The Future With You
Rob

**Comment by broroduvce9p** [comment]
LAPO XLM / BSC Swap machine (turned off)
https://i.ibb.co/kXC7v2f/lapo1.jpg
https://i.ibb.co/fHK4fHt/lapo2.jpg
https://i.ibb.co/SQzD0Xw/lapo3.jpg


Transactions between the networks show the inconsistency in receiving/sending in favor of the developers for the last two years. Such manipulation could steal not only xlm, but also bnb.
Probably deserved the label #malicious and #unsafe.

**Comment by CryptoHobbyist** [comment]
Hello @broroduvce9p

I tend to personally think that is the case. But you can agree that it could also be seen as a failed bridging attempt that for some reason felt they needed to mint a new token to do this.

There are so many ill conceived projects that believe that minting a token will bring magic money to make their project work.

Rob

**Comment by CryptoHobbyist** [comment]
Hello @broroduvce9p

This issue is being closed. Please feel free to reopen it if you have new information.

Looking Towards The Future With You,
Rob
