### ISSUE TITLE
Add Issuer For Stellarlogy

### ISSUE THREAD

**Issue by stellarlogy** [stellar-expert/public-directory#596]
Token - STL
Issuer: GBFE66R77SPV2XOBSVGDSAHLBY5GCMYOE6G6UMCN47RNYWTHZJUFML5N

**Comment by CryptoHobbyist** [comment]
Hello @stellarlogy,

With over 120,000 different tokens on the Stellar Blockchain it is not practical to lable/tag all assests in our database.
With initial review this STL project just started, has very few holders and very little trading and is registered through NameCheap (which is one of the very favorites of many scams.)

When Stellar.expert fully researches and lables projects it kind of suggests a legitimancy that we have verified that a project. That is the reason we don't typically tag unproven projects. On the other hand if projects have gone through a preparation system and can show the backing of a well established system then these qualifiers are factored in. That is why you might see project born out of an established business incubator, or program like the Stellar Community Fund they might be labeled at the onset.

As you develop and strengthen your project please re contact us to do a full review.

Looking Towards The Future With You,
Rob

**Comment by stellarlogy** [comment]
Hello @CryptoHobbyist 

We have hired a team in order to complete the background check of projects that would be verified and listed by us. Which is scheduled to be updated this week on the website.

**Comment by CryptoHobbyist** [comment]
Hello @stellarlogy,

If you ever see any tokens trying to counterfeit your project please let us know.

**Comment by CryptoHobbyist** [comment]
> Hello @CryptoHobbyist
> 
> We have hired a team in order to complete the background check of projects that would be verified and listed by us. Which is scheduled to be updated this week on the website.

Does the above mean that there be somekind of KYC or that you are being compliant with some kind of legal jurisdictiion? All of that kind of information and any company registrations should be included on you website. Being on an open listing for companies is not the same as a State registration record/listing on their site. **These are not required to be labeled on Stellar Expert, but go a long way to establish creditability with users.**

When your project is detailed on your website let us know. 

Rob

**Comment by stellarlogy** [comment]
> Hello @stellarlogy,
> 
> If you ever see any tokens trying to counterfeit your project please let us know.

Yes, Any tokens trying to counterfeit our project will be reported on immediate basis. thanks

**Comment by stellarlogy** [comment]
> > Hello @CryptoHobbyist
> > We have hired a team in order to complete the background check of projects that would be verified and listed by us. Which is scheduled to be updated this week on the website.
> 
> Does the above mean that there be somekind of KYC or that you are being compliant with some kind of legal jurisdictiion? All of that kind of information and any company registrations should be included on you website. Being on an open listing for companies is not the same as a State registration record/listing on their site. **These are not required to be labeled on Stellar Expert, but go a long way to establish creditability with users.**
> 
> When your project is detailed on your website let us know.
> 
> Rob

Certainly; We are following a strict process wherein projects would be required to complete their KYC with us before we would be listing them.. 

All the information and company registrations will be included on our website and mobile app. 

Labeling on stellar expert will not be done until creditability is established with the users overtime.

We will update you once our project is detailed on our website.  thanks @CryptoHobbyist

**Comment by stellarlogy** [comment]
Hello @CryptoHobbyist 

We have updated our website V0.2 with further information stellarlogy.com ; Next update is scheduled in the upcoming week. So if it's good to go we can have our project labeled. Thanks

**Comment by CryptoHobbyist** [comment]
Hello @stellarlogy,

You are still an unproven project and there are couple some blaring issues one of which is falsified DEVs listed on your website.
https://lens.google.com/search?ep=gsbubu&hl=en&re=df&p=AbrfA8ra2HDLwvIan2FGvDrQOrjC6YyNh1mw-2Kj4l68JR_yZ8FvuMY1x8W1MWEWy_xkdsnAro0naThY3Z_N3OgEOZR1MufszeSYoGj9XX-dJ387AYkqC4S222cR77aCt9vXEHuwRzTG7GIvtXfeuN7niioeDXqAG4w4WEyrxw6admstTrZpxstL4yArX_fSqfezKONx7HGG9tXFRwZv6NiO#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKRFExTVRnNE5ERTJMVGs1TXpNdE5EQTBOUzA1T1dSbUxUSmpaRFV6WTJSaVpEZ3hOeElmTURsM1gwMXdjV2hHY1RCUmEwaDRiR3BST0hJemVEbHZXbVJVVVhKNFp3PT0iXQ==

https://lens.google.com/search?ep=gsbubu&hl=en&re=df&p=AbrfA8ox7cTjm5_vkKeGXZlEpe6IlqziCpZiCWdF8Q488Kj8VlNQi4h7LhsNos-H0O8MVAA_iKfvmJBGUzplrmTMWeUaWhJjox8w3gEWmYCczZSHyuw2p6HwWQzHFlQMUO2-NIs19LVewrTcRBG1zjtWFAzH_UsnUKhNdIGLNrBQNYTEdYdIwwTon3abz8GaTMQ5odT0edBqva1DrsIR6ftF#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDEsIkVrY0tKRGxoTVRKbU5tWTRMV000TjJVdE5HTTBOUzFoT1RNM0xUY3laVFprTXpKaE9ETm1OaElmZHpsclFUVkthR1l0VXpoa1NVVXhUR3gwZUVKVlRIQlpPR2xFVW5KNFp3PT0iLG51bGwsbnVsbCxbW251bGwsbnVsbCwiaXAtMSJdLFsiY2IyYTE1NzQtMWZmNC00OGUyLTg5NzYtNzg2YWI2YjEyZjQyIl1dLDEsbnVsbCxbbnVsbCxudWxsLFsyMTk1MSw4MjMyLDcwOTg5LDU0MjY4XV0sW251bGwsbnVsbCxbXV1d

I only checked the first two.

Rob

**Comment by CryptoHobbyist** [comment]
Hello @stellarlogy,

Please remember that being labled on our database at Stellar.expert has no effect on your token project using the Stellar Blockchain. As you already know the Stellar Blockchain is a total DeFi system.

Rob

**Comment by stellarlogy** [comment]
> Hello @stellarlogy,
> 
> You are still an unproven project and there are couple some blaring issues one of which is falsified DEVs listed on your website. https://lens.google.com/search?ep=gsbubu&hl=en&re=df&p=AbrfA8ra2HDLwvIan2FGvDrQOrjC6YyNh1mw-2Kj4l68JR_yZ8FvuMY1x8W1MWEWy_xkdsnAro0naThY3Z_N3OgEOZR1MufszeSYoGj9XX-dJ387AYkqC4S222cR77aCt9vXEHuwRzTG7GIvtXfeuN7niioeDXqAG4w4WEyrxw6admstTrZpxstL4yArX_fSqfezKONx7HGG9tXFRwZv6NiO#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKRFExTVRnNE5ERTJMVGs1TXpNdE5EQTBOUzA1T1dSbUxUSmpaRFV6WTJSaVpEZ3hOeElmTURsM1gwMXdjV2hHY1RCUmEwaDRiR3BST0hJemVEbHZXbVJVVVhKNFp3PT0iXQ==
> 
> https://lens.google.com/search?ep=gsbubu&hl=en&re=df&p=AbrfA8ox7cTjm5_vkKeGXZlEpe6IlqziCpZiCWdF8Q488Kj8VlNQi4h7LhsNos-H0O8MVAA_iKfvmJBGUzplrmTMWeUaWhJjox8w3gEWmYCczZSHyuw2p6HwWQzHFlQMUO2-NIs19LVewrTcRBG1zjtWFAzH_UsnUKhNdIGLNrBQNYTEdYdIwwTon3abz8GaTMQ5odT0edBqva1DrsIR6ftF#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDEsIkVrY0tKRGxoTVRKbU5tWTRMV000TjJVdE5HTTBOUzFoT1RNM0xUY3laVFprTXpKaE9ETm1OaElmZHpsclFUVkthR1l0VXpoa1NVVXhUR3gwZUVKVlRIQlpPR2xFVW5KNFp3PT0iLG51bGwsbnVsbCxbW251bGwsbnVsbCwiaXAtMSJdLFsiY2IyYTE1NzQtMWZmNC00OGUyLTg5NzYtNzg2YWI2YjEyZjQyIl1dLDEsbnVsbCxbbnVsbCxudWxsLFsyMTk1MSw4MjMyLDcwOTg5LDU0MjY4XV0sW251bGwsbnVsbCxbXV1d
> 
> I only checked the first two.
> 
> Rob

Hello @CryptoHobbyist 

The "About Us" part on the website is the template which we are testing with our mobile app compatibility; Please ignore the images of our team members as they aren't updated yet; In the upcoming week we are coming up with the updated version of our website StellarlogyV0.3.

At same; yes we know that being labled on Stellar.expert database will have no effect on our project but as we would be issuing tokens for other projects post their KYC; It's essential for us to be labeled as a project.

We already have received a couple of applications; But we aren't proceeding until the final website update is established and we get our project labeled.

Thanks, Zeus.

**Comment by CryptoHobbyist** [comment]
Hello @stellarlogy,

Let me know when things are done. and can be fully reviewed.

Rob

**Comment by stellarlogy** [comment]
Hello @CryptoHobbyist 

Our website update V0.3 is completed. It can be reviewed now. Thanks.

**Comment by CryptoHobbyist** [comment]
Hello @stellarlogy,

Please feel free to reopen this issue with any new information.

Looking Towards The Future With You,
Rob
