### ISSUE TITLE
Add [XAU CL] #issuer GBCB4WO6J4ET55RWK2SVX76LUQ4PQ7TCDHG2YFILQML7D6XR3HACLXAU

### ISSUE THREAD

**Issue by exchangecl** [stellar-expert/public-directory#615]
Recently, my token was flagged as #unsafe. Please guide me on best practices to avoid these kinds of issues. Most of the issued tokens are backed by liquidity pools.

**Comment by CryptoHobbyist** [comment]
The new information has been modifieid.

Please stop changing the information to it "anchored" and sounding like it is connected to real gold. If it happens again the flagging will be permanent since this will be looked at a intentional and repeated deception.
